# Generated by Django 3.0.3 on 2020-02-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200207_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
