# Generated by Django 3.0.3 on 2020-02-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20200208_1428'),
        ('articles', '0004_article_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-published_date',)},
        ),
        migrations.AddField(
            model_name='article',
            name='featured_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_cover', to='media.Photo'),
        ),
    ]
