export const articleActions = {
  GET_ARTICLES: "GET_ARTICLES",
  GET_ARTICLES_COUNT: "GET_ARTICLES_COUNT",
  CHANGE_LIST_PAGE: "CHANGE_ARTICLE_LIST_PAGE",
  READ_ARTICLE: "READ_ARTICLE"
};

export const profileActions = {
  GET_PROFILE: "GET_PROFILE"
};
