export const storyActions = {
  GET_STORY: "GET_STORY",
  GET_STORY_COUNT: "GET_STORY_COUNT",
  CHANGE_LIST_PAGE: "CHANGE_ARTICLE_LIST_PAGE",
  READ_STORY: "READ_STORY",
  GET_NEW_STORY_STATUS: "GET_NEW_STORY_STATUS"
};

export const profileActions = {
  GET_PROFILE: "GET_PROFILE",
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT'
};

export const mediaActions = {
  ADD_NEW_PHOTO: 'ADD_NEW_PHOTO'
}