# Generated by Django 3.0.1 on 2020-02-08 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20200208_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
